# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youtube.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(497, 122)
        Form.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.bt_download = QtWidgets.QPushButton(Form)
        self.bt_download.setGeometry(QtCore.QRect(400, 40, 83, 25))
        self.bt_download.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.bt_download.setObjectName("bt_download")
        self.txt_link = QtWidgets.QLineEdit(Form)
        self.txt_link.setGeometry(QtCore.QRect(80, 10, 401, 25))
        self.txt_link.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_link.setObjectName("txt_link")
        self.txt_nome = QtWidgets.QLineEdit(Form)
        self.txt_nome.setGeometry(QtCore.QRect(80, 40, 181, 25))
        self.txt_nome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_nome.setObjectName("txt_nome")
        self.lb_link = QtWidgets.QLabel(Form)
        self.lb_link.setGeometry(QtCore.QRect(10, 10, 62, 17))
        self.lb_link.setStyleSheet("")
        self.lb_link.setObjectName("lb_link")
        self.lb_nome = QtWidgets.QLabel(Form)
        self.lb_nome.setGeometry(QtCore.QRect(10, 40, 51, 17))
        self.lb_nome.setStyleSheet("")
        self.lb_nome.setObjectName("lb_nome")
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(270, 40, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setStyleSheet("color: rgb(0, 255, 0);")
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber.setDigitCount(8)
        self.lcdNumber.setObjectName("lcdNumber")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(270, 68, 211, 51))
        self.groupBox.setObjectName("groupBox")
        self.lb_download = QtWidgets.QLabel(self.groupBox)
        self.lb_download.setGeometry(QtCore.QRect(10, 25, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_download.setFont(font)
        self.lb_download.setStyleSheet("color: rgb(0, 85, 255);")
        self.lb_download.setObjectName("lb_download")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 70, 251, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(10, 90, 251, 21))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.lb_nome_2 = QtWidgets.QLabel(self.splitter)
        self.lb_nome_2.setStyleSheet("")
        self.lb_nome_2.setObjectName("lb_nome_2")
        self.rb_mp3 = QtWidgets.QRadioButton(self.splitter)
        self.rb_mp3.setStyleSheet("")
        self.rb_mp3.setChecked(True)
        self.rb_mp3.setObjectName("rb_mp3")
        self.rb_mp4 = QtWidgets.QRadioButton(self.splitter)
        self.rb_mp4.setStyleSheet("")
        self.rb_mp4.setObjectName("rb_mp4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Youtube - Download"))
        self.bt_download.setText(_translate("Form", "Download!"))
        self.lb_link.setText(_translate("Form", "Link:"))
        self.lb_nome.setText(_translate("Form", "Nome:"))
        self.groupBox.setTitle(_translate("Form", "Tempo - Download"))
        self.lb_download.setText(_translate("Form", "Tempo: 00:00"))
        self.lb_nome_2.setText(_translate("Form", "Formato:"))
        self.rb_mp3.setText(_translate("Form", "MP3"))
        self.rb_mp4.setText(_translate("Form", "MP4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
